# Generated by Django 3.2.13 on 2022-05-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status_sending',
            field=models.IntegerField(choices=[(1, 'Отправлено'), (0, 'Ошибка при отправке'), (2, 'Создано')], default=2, verbose_name='Статус отправки'),
        ),
    ]
